# sonar-project.properties
# Substitua <seu-usuario> pelo seu usuário/organização do SonarCloud
sonar.projectKey=chavemaximus-advancedtopics-sys
sonar.organization=sys_maximus-org
sonar.projectName=advancedTopics-SYS

# Fontes analisadas
sonar.sources=catalog-service/src,order-service/src,payment-service/src,user-service/src,game-store-frontend/src

# Excluir gerados, migrações e arquivos de teste do escopo principal
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/coverage/**,**/*.test.ts

# Relatórios de cobertura gerados pelo Jest (lcov)
sonar.javascript.lcov.reportPaths=catalog-service/coverage/lcov.info,order-service/coverage/lcov.info,payment-service/coverage/lcov.info,user-service/coverage/lcov.info,game-store-frontend/coverage/lcov.info